AWSTemplateFormatVersion: '2010-09-09'
Description: 'RevOps AI Framework - Webhook Gateway Infrastructure'

Parameters:
  EnvironmentName:
    Type: String
    Default: 'prod'
    Description: Environment name for resource naming
    
  ManagerAgentFunctionName:
    Type: String
    Default: 'revops-manager-agent-wrapper'
    Description: Name of the Manager Agent wrapper Lambda function
    
  BedrockAgentId:
    Type: String
    Default: 'PVWGKOWSOT'
    Description: Bedrock Agent ID for the Manager Agent
    
  BedrockAgentAliasId:
    Type: String
    Default: 'TSTALIASID'
    Description: Bedrock Agent Alias ID for the Manager Agent
    
  DealAnalysisWebhookUrl:
    Type: String
    Default: ''
    Description: Webhook URL for deal analysis responses
    
  DataAnalysisWebhookUrl:
    Type: String
    Default: ''
    Description: Webhook URL for data analysis responses
    
  LeadAnalysisWebhookUrl:
    Type: String
    Default: ''
    Description: Webhook URL for lead analysis responses
    
  GeneralWebhookUrl:
    Type: String
    Default: ''
    Description: Fallback webhook URL for general responses
    
  LogLevel:
    Type: String
    Default: 'INFO'
    AllowedValues: ['DEBUG', 'INFO', 'WARNING', 'ERROR']
    Description: Lambda function log level

Resources:
  # Dead Letter Queue for failed outbound webhooks
  OutboundWebhookDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${EnvironmentName}-revops-webhook-outbound-dlq'
      MessageRetentionPeriod: 1209600
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: RevOpsAI
        - Key: Component
          Value: WebhookGateway

  # SQS Queue for outbound webhook delivery
  OutboundWebhookQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${EnvironmentName}-revops-webhook-outbound-queue'
      MessageRetentionPeriod: 1209600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt OutboundWebhookDLQ.Arn
        maxReceiveCount: 5
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: RevOpsAI
        - Key: Component
          Value: WebhookGateway

  # IAM Role for Manager Agent Wrapper Lambda
  ManagerAgentWrapperRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${EnvironmentName}-revops-manager-agent-wrapper-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ManagerAgentWrapperPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Allow invoking Bedrock Agent
              - Effect: Allow
                Action:
                  - bedrock:InvokeAgent
                Resource: 
                  - !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:agent/${BedrockAgentId}'
              # CloudWatch Logs
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: RevOpsAI
        - Key: Component
          Value: ManagerAgentWrapper

  # Lambda function for Manager Agent wrapper
  ManagerAgentWrapperFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref ManagerAgentFunctionName
      Runtime: python3.9
      Handler: manager_agent_wrapper.lambda_handler
      Role: !GetAtt ManagerAgentWrapperRole.Arn
      Code:
        ZipFile: |
          # Placeholder - will be updated by deployment script
          import json
          def lambda_handler(event, context):
              return {'success': False, 'error': 'Function not yet deployed'}
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          BEDROCK_AGENT_ID: !Ref BedrockAgentId
          BEDROCK_AGENT_ALIAS_ID: !Ref BedrockAgentAliasId
          LOG_LEVEL: !Ref LogLevel
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: RevOpsAI
        - Key: Component
          Value: ManagerAgentWrapper

  # CloudWatch Log Group for Manager Agent wrapper
  ManagerAgentWrapperLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ManagerAgentWrapperFunction}'
      RetentionInDays: 30

  # IAM Role for Webhook Gateway Lambda
  WebhookGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${EnvironmentName}-revops-webhook-gateway-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: WebhookGatewayPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Allow invoking Manager Agent
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: 
                  - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ManagerAgentFunctionName}'
              # Allow SQS operations for outbound queue
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:GetQueueAttributes
                Resource:
                  - !GetAtt OutboundWebhookQueue.Arn
              # CloudWatch Logs
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: RevOpsAI
        - Key: Component
          Value: WebhookGateway

  # Lambda function for webhook gateway
  WebhookGatewayFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${EnvironmentName}-revops-webhook-gateway'
      Runtime: python3.9
      Handler: webhook_handler.lambda_handler
      Role: !GetAtt WebhookGatewayRole.Arn
      Code:
        ZipFile: |
          # Placeholder - will be updated by deployment script
          import json
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': json.dumps('Function not yet deployed')}
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          MANAGER_AGENT_FUNCTION_NAME: !Ref ManagerAgentFunctionName
          OUTBOUND_WEBHOOK_QUEUE_URL: !Ref OutboundWebhookQueue
          DEAL_ANALYSIS_WEBHOOK_URL: !Ref DealAnalysisWebhookUrl
          DATA_ANALYSIS_WEBHOOK_URL: !Ref DataAnalysisWebhookUrl
          LEAD_ANALYSIS_WEBHOOK_URL: !Ref LeadAnalysisWebhookUrl
          GENERAL_WEBHOOK_URL: !Ref GeneralWebhookUrl
          LOG_LEVEL: !Ref LogLevel
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: RevOpsAI
        - Key: Component
          Value: WebhookGateway

  # CloudWatch Log Group for webhook gateway
  WebhookGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${WebhookGatewayFunction}'
      RetentionInDays: 30

  # API Gateway for webhook endpoint
  WebhookApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${EnvironmentName}-revops-webhook-gateway-api'
      Description: 'API Gateway for RevOps AI Framework Webhook Gateway'
      EndpointConfiguration:
        Types:
          - REGIONAL
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: RevOpsAI
        - Key: Component
          Value: WebhookGateway

  # API Gateway Resource for webhook endpoint
  WebhookResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref WebhookApi
      ParentId: !GetAtt WebhookApi.RootResourceId
      PathPart: 'webhook'

  # API Gateway Method for POST to webhook
  WebhookMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref WebhookApi
      ResourceId: !Ref WebhookResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebhookGatewayFunction.Arn}/invocations'
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: Empty
        - StatusCode: 400
          ResponseModels:
            application/json: Empty
        - StatusCode: 500
          ResponseModels:
            application/json: Empty

  # Health check resource and method
  HealthResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref WebhookApi
      ParentId: !GetAtt WebhookApi.RootResourceId
      PathPart: 'health'

  HealthMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref WebhookApi
      ResourceId: !Ref HealthResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebhookGatewayFunction.Arn}/invocations'

  # API Gateway Deployment
  WebhookApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - WebhookMethod
      - HealthMethod
    Properties:
      RestApiId: !Ref WebhookApi
      StageName: !Ref EnvironmentName

  # Lambda permission for API Gateway
  WebhookGatewayApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebhookGatewayFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub '${WebhookApi}/*/POST/webhook'

  # Lambda permission for API Gateway health check
  WebhookGatewayHealthPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebhookGatewayFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub '${WebhookApi}/*/GET/health'

Outputs:
  WebhookEndpoint:
    Description: 'Webhook Gateway API endpoint URL'
    Value: !Sub 'https://${WebhookApi}.execute-api.${AWS::Region}.amazonaws.com/${EnvironmentName}/webhook'
    Export:
      Name: !Sub '${EnvironmentName}-revops-webhook-endpoint'

  HealthCheckEndpoint:
    Description: 'Health check endpoint URL'
    Value: !Sub 'https://${WebhookApi}.execute-api.${AWS::Region}.amazonaws.com/${EnvironmentName}/health'
    Export:
      Name: !Sub '${EnvironmentName}-revops-webhook-health-endpoint'

  OutboundWebhookQueueUrl:
    Description: 'SQS Queue URL for outbound webhook delivery'
    Value: !Ref OutboundWebhookQueue
    Export:
      Name: !Sub '${EnvironmentName}-revops-outbound-webhook-queue-url'

  WebhookGatewayFunctionName:
    Description: 'Webhook Gateway Lambda function name'
    Value: !Ref WebhookGatewayFunction
    Export:
      Name: !Sub '${EnvironmentName}-revops-webhook-gateway-function-name'

  WebhookGatewayFunctionArn:
    Description: 'Webhook Gateway Lambda function ARN'
    Value: !GetAtt WebhookGatewayFunction.Arn
    Export:
      Name: !Sub '${EnvironmentName}-revops-webhook-gateway-function-arn'