AWSTemplateFormatVersion: '2010-09-09'
Description: 'Enhanced Agent Tracing Infrastructure for RevOps AI Framework'

Parameters:
  ProjectName:
    Type: String
    Default: 'revops-ai'
    Description: 'Project name for resource naming'
  
  RetentionDays:
    Type: Number
    Default: 7
    Description: 'Log retention period for debugging'

Resources:
  # Conversation-level tracing
  ConversationTraceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/${ProjectName}/conversation-trace'
      RetentionInDays: !Ref RetentionDays
      
  # Agent collaboration tracing  
  AgentCollaborationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/${ProjectName}/agent-collaboration'
      RetentionInDays: !Ref RetentionDays
      
  # Data operations tracing
  DataOperationsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/${ProjectName}/data-operations'
      RetentionInDays: !Ref RetentionDays
      
  # Decision logic tracing
  DecisionLogicLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/${ProjectName}/decision-logic'
      RetentionInDays: !Ref RetentionDays
      
  # Error analysis tracing
  ErrorAnalysisLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/${ProjectName}/error-analysis'
      RetentionInDays: !Ref RetentionDays

  # Agent Chain Tracing Dashboard
  AgentTracingDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${ProjectName}-agent-tracing'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "log",
              "x": 0, "y": 0, "width": 24, "height": 6,
              "properties": {
                "query": "SOURCE '/aws/${ProjectName}/conversation-trace'\n| fields @timestamp, correlation_id, user_query, agent_response_summary\n| filter @message like /CONVERSATION_START/\n| sort @timestamp desc\n| limit 20",
                "region": "us-east-1",
                "title": "Recent Conversations",
                "view": "table"
              }
            },
            {
              "type": "log", 
              "x": 0, "y": 6, "width": 12, "height": 6,
              "properties": {
                "query": "SOURCE '/aws/${ProjectName}/agent-collaboration'\n| fields @timestamp, correlation_id, source_agent, target_agent, collaboration_type\n| filter @message like /AGENT_INVOKE/\n| sort @timestamp desc\n| limit 20",
                "region": "us-east-1", 
                "title": "Agent Collaborations",
                "view": "table"
              }
            },
            {
              "type": "log",
              "x": 12, "y": 6, "width": 12, "height": 6, 
              "properties": {
                "query": "SOURCE '/aws/${ProjectName}/error-analysis'\n| fields @timestamp, correlation_id, error_type, error_message\n| filter @message like /ERROR/\n| sort @timestamp desc\n| limit 20",
                "region": "us-east-1",
                "title": "Recent Errors", 
                "view": "table"
              }
            },
            {
              "type": "log",
              "x": 0, "y": 12, "width": 24, "height": 6,
              "properties": {
                "query": "SOURCE '/aws/${ProjectName}/data-operations'\n| fields @timestamp, correlation_id, operation_type, data_source, query_summary\n| filter @message like /DATA_OPERATION/\n| sort @timestamp desc\n| limit 20", 
                "region": "us-east-1",
                "title": "Data Operations",
                "view": "table"
              }
            }
          ]
        }

  # CloudWatch Insights Saved Queries
  ConversationFlowQuery:
    Type: AWS::Logs::QueryDefinition
    Properties:
      Name: !Sub '${ProjectName}-conversation-flow'
      LogGroupNames:
        - !Ref ConversationTraceLogGroup
        - !Ref AgentCollaborationLogGroup
        - !Ref DataOperationsLogGroup
      QueryString: |
        fields @timestamp, correlation_id, event_type, agent_name, message_summary
        | filter correlation_id = "CORRELATION_ID_PLACEHOLDER"
        | sort @timestamp asc

  AgentChainAnalysisQuery:
    Type: AWS::Logs::QueryDefinition  
    Properties:
      Name: !Sub '${ProjectName}-agent-chain-analysis'
      LogGroupNames:
        - !Ref AgentCollaborationLogGroup
      QueryString: |
        fields @timestamp, correlation_id, source_agent, target_agent, collaboration_type, reasoning
        | filter correlation_id = "CORRELATION_ID_PLACEHOLDER"
        | sort @timestamp asc

  ErrorAnalysisQuery:
    Type: AWS::Logs::QueryDefinition
    Properties:
      Name: !Sub '${ProjectName}-error-analysis'
      LogGroupNames:
        - !Ref ErrorAnalysisLogGroup
      QueryString: |
        fields @timestamp, correlation_id, error_type, error_message, stack_trace, agent_context
        | filter @timestamp >= "START_TIME_PLACEHOLDER" and @timestamp <= "END_TIME_PLACEHOLDER"
        | sort @timestamp desc

Outputs:
  ConversationTraceLogGroup:
    Description: 'Log group for conversation-level tracing'
    Value: !Ref ConversationTraceLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-ConversationTraceLogGroup'
      
  AgentCollaborationLogGroup:
    Description: 'Log group for agent collaboration tracing'
    Value: !Ref AgentCollaborationLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-AgentCollaborationLogGroup'
      
  DataOperationsLogGroup:
    Description: 'Log group for data operations tracing'
    Value: !Ref DataOperationsLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-DataOperationsLogGroup'
      
  DecisionLogicLogGroup:
    Description: 'Log group for decision logic tracing'
    Value: !Ref DecisionLogicLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-DecisionLogicLogGroup'
      
  ErrorAnalysisLogGroup:
    Description: 'Log group for error analysis'
    Value: !Ref ErrorAnalysisLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-ErrorAnalysisLogGroup'
      
  DashboardURL:
    Description: 'CloudWatch Dashboard URL for agent tracing'
    Value: !Sub 'https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=${ProjectName}-agent-tracing'